### ISSUE TITLE
Throw a warning when the user specifies an invalid starting measure...

### ISSUE THREAD

**Issue by samussiah** [RhoInc/safety-outlier-explorer#103]
...and default to an existent measure.

# Test notes
* Invalid measure:
  * Specify an invalid initially displayed measure, i.e. one that doesn't appear in the data. (Fill in some dummy text in the "Initially Displayed Measure" field in Settings).
  * Check that a warning appears in the console noting that the specified measure is invalid.
  * Verify that the measure dropdown defaults to an existent measure.
* Measure without units:
  * Specify a valid initially displayed measure but without units, e.g. _Temperature_.
  * Check that a warning appears in the console noting that the specified measure does not include units.
  * Verify that the measure dropdown defaults to the specified measure _with_ units.

**Comment by danedexF5** [comment]
@samussiah This looks good except for the logging. When I check the Full Log I don't see anything flagged.

**Comment by samussiah** [comment]
sorry @danedexF5 , I meant to say the warning print to the console, not the log at the top in CAT.  As for the Temperature issue in IE, I'm not sure what's going on there.  Let's ignore for now as long as it's rendering by default.  Might just be a CAT issue.

**Comment by danedexF5** [comment]
This is good outside of the IE issue.
