### ISSUE TITLE
Add support for custom tooltips

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/safety-outlier-explorer#109]
Specific request is for Date to be added to the tooltip

**Comment by jwildfire** [comment]
Adding `config.tooltip_cols` which takes an array of col/label objects and adds those values to the end of the standard point tooltips. `settings = {tooltip_cols: [{label:"Date",value_col:"DT"}]};` gives: 
<img width="1132" alt="screen shot 2018-10-03 at 2 35 47 pm" src="https://user-images.githubusercontent.com/3680095/46440889-ac157f80-c719-11e8-9dfe-709753090ecb.png">

**Comment by jwildfire** [comment]
## Test Notes

Confirm that date is added to the standard tooltip with these settings: 

```
{
  tooltip_cols: [{
    label:"Date",
    value_col:"DT"
  }]
}
```

**Comment by rchronowic** [comment]
Passed testing in both Firefox and Chrome, using CAT.

**Comment by dschwentker** [comment]
Per Ryan, tested and passed.
