### ISSUE TITLE
Small multiple size error in refactor

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/safety-outlier-explorer#13]
See project 185

**Comment by jwildfire** [comment]
Worth researching - might bump from 1.3 if it requires a lot of work.

**Comment by samussiah** [comment]
Looks like the blankyblanks are hidden non-continuous measures.  Should be a pretty easy fix.

**Comment by samussiah** [comment]
jk, not all multiples are created equally.  some are of average height, some short, some taller.  the taller ones won't let the shorter ones `float left`.  tis a shame.  we'll have to teach them a lesson and remove their `resizability`.
