### ISSUE TITLE
Add stratification with line and point color.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/safety-outlier-explorer#148]
a la safety-results-over-time:
```
groups: [
  { value_col: 'ARM', label: 'Treatment Group' }
]
```
# Test Notes
- Add the following code snippet to the settings in CAT:
 groups: [
                {
                    value_col: 'ARM',
                    label: 'Treatment Group'
                },
                {
                    value_col: 'SEX',
                    label: 'Sex'
                }
            ],
- Verify that the chart now has a 'Group by' control, the points and lines are colored by the categories of that group, and that a legend appears at the bottom corresponding to the current grouping and colors
- Change the 'Group by' Control and verify that the chart and legend reflects the new grouping

**Comment by danedexF5** [comment]
Approved
