### ISSUE TITLE
Add setting to sort measures other than alphanumerically.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/safety-outlier-explorer#149]
Allow values in the measure dropdown to be ordered based on a variable like `PARAMN` in the ADaM data standard.  Going with `TESTN` because the rest of the data mappings are based on the SDTM naming convention.

# Test Notes
- Download the default adbds.csv test file from CAT
- Delete all of the data after the 5th row
- Add a column named 'TESTN'
- Add the values 1 2 3 4 5 to each of the cells of the corresponding rows under column TESTN
- Load this updated csv into CAT
- Verify that the measures appear in the Measure filter in the same order as the uploaded csv and not in alphabetical order

**Comment by danedexF5** [comment]
Approved
