### ISSUE TITLE
Allow user to specify start and all properties of filters.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/safety-outlier-explorer#151]
# Test Notes
- Add the following to the settings in CAT:  
"filters": [
        {
            "value_col": "ARM",
            "label": "Treatment Group",
            "start": "Placebo"
        }
    ],
- Verify that a filter appears with the name 'Treatment Group' that subsets the data appropriately when used
- Verify that no 'All' option appears in the filter dropdown
- Verify that on renderering, the chart is already filtered by 'Placebo' and that this is reflected by the drop down

**Comment by pburnsdata** [comment]
@samussiah I added test notes for these - lemme know if anything seems off on them, or feel free to edit them!

**Comment by danedexF5** [comment]
Approved
