### ISSUE TITLE
Add Participant Information to details view

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/safety-outlier-explorer#19]
Jack's request for a Participant Profile can be mostly covered by adding participant information (sex, age, ID) to the details list on the drill down for each test.

**Comment by jwildfire** [comment]
Add demographic info next to the ID shown (e.g. "All Measures for 01-708-1316") in the small multiple detail view. Probably easiest  to add a new "detail_vars" option.

**Comment by samussiah** [comment]
ASL?  huehehhee

Defaulting to age/sex/race, removing columns not present in data as needed.
