### ISSUE TITLE
Make axes ranges stay consistent when using a filter

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/safety-outlier-explorer#22]
From Meagan Spychala on 9/19:

"It would be really useful if the axes’ ranges stayed consistent when using a filter.  For example, we were looking at a longitudinal graphic of systolic blood pressure across several sites, but each site’s graphic had an updated vertical range to fit that site, it did  the use aggregate of the data (i.e. if the SBP for the study as a whole was 70 to 160, but a site’s range was 90-120, the 90-120 would be the vertical axis range for that site only) .  Because the range of the vertical (SBP) and horizontal (Visit) axes can change, it is harder to see if the sites were in line with each other or if there was an outlying site.  I think it’s appropriate to have the range of the axes change depending on the measure (for example, SBP vs. DBP), but once you pick a measure, the axes’ range should be held constant based upon the overall data to be able to identify potential trends."

**Comment by jwildfire** [comment]
We can likely handle this by changing the default setting for webcharts y-axis `behavior` setting.

**Comment by samussiah** [comment]
Branching off #28 .
