### ISSUE TITLE
Create example showing filter/highlight behavior by Query status

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/safety-outlier-explorer#27]

**Comment by samussiah** [comment]
[with modals](http://bl.ocks.org/samussiah/raw/afe3abbce6b574926536bb12292a4e72/)

**Comment by samussiah** [comment]
Scaling back to generic custom marks.

**Comment by samussiah** [comment]
[with custom marks](http://bl.ocks.org/samussiah/8678a024c694440876220547e9475340)
