### ISSUE TITLE
Missing values are being plotted

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/safety-outlier-explorer#41]
![outlier_explorer_plotting](https://cloud.githubusercontent.com/assets/14914918/22485070/29d7e850-e7d2-11e6-811f-1650aaac32d1.JPG)

233 is plotting points for missing values

**Comment by jwildfire** [comment]
@brittsikora @samussiah What are these values saved as in the data? "NA"? ""?  something else? We should probably fix this in either 2.0.0 or ASAP with a bug fix in 2.0.1.

**Comment by jwildfire** [comment]
Adding to 2.0 and assigning @samussiah for now.

**Comment by jwildfire** [comment]
Looks like maybe this is resolved in the most recent build. If so, go ahead and close the issue.
