### ISSUE TITLE
Small Multiples not rendering properly

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/safety-outlier-explorer#42]
![outlier_explorer_weak](https://cloud.githubusercontent.com/assets/14914918/22485093/3be5ed08-e7d2-11e6-84bb-c2cec745eb2b.JPG)

Small multiples are misbehaving

**Comment by jwildfire** [comment]
@samussiah @brittsikora Is this happening consistently or just in certain situation?

**Comment by jwildfire** [comment]
Looks like maybe this is resolved in the most recent build. If so, go ahead and close the issue.
