### ISSUE TITLE
Add Ability to Filter by Additional Variables

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/safety-outlier-explorer#5]

**Comment by jwildfire** [comment]
Not sure what this one means. @brittsikora to clarify or close.

**Comment by brittsikora** [comment]
Found in the original issue: Add the ability to sort by other variables such as gender, site, dose, etc.

**Comment by jwildfire** [comment]
duplicate of https://github.com/RhoInc/safety-outlier-explorer/issues/8
