### ISSUE TITLE
Show all time points in small multiples

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/safety-outlier-explorer#54]
Current State: `x.domain` is for the small multiples is currently set using the current chart. This causes problems with x.domain changes between measures since only the timepoints for the current chart are shown in the multiples. 

Fix: Let x-scale vary between small multiples.

**Comment by emmorris** [comment]
@jwildfire is it fine for me to close this one now?  It looks like it was resolved as part of 2.0.3.

**Comment by jwildfire** [comment]
Yes - closing.
