### ISSUE TITLE
Add Ability to Set Y-Axis Limits

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/safety-outlier-explorer#6]
Auto-scaling was throwing people off, so add ability to set limits. Or toggle between log axis and linear.

**Comment by jwildfire** [comment]
related to #22. We'll do some kind of initial fix in 1.3. Might want to create a separate issue for the log/linear toggle.

**Comment by jwildfire** [comment]
Bumping to v1.4.0

**Comment by bzkrouse** [comment]
@jwildfire was going to suggest log/linear toggle

**Comment by rtbailey** [comment]
Another case that Jack has asked about is when a single outlier makes the rest of the chart unreadable/unsuable.  See screenshot:    
![image](https://user-images.githubusercontent.com/10886203/32507036-50dc3898-c3b4-11e7-94d3-5a42f462d360.png)

Incidentally, Jeremy told Jack we could implement this solution soon, so we should bump it up in priority.

**Comment by samussiah** [comment]
Test notes:

* Three new controls appear:
** one that controls the lower limit of the y-axis
** one that controls the upper limit of the y-axis
** one that resets the y-axis to the minimum and maximum values in the data
* Typing in a number into either the lower limit or upper limit control updates the y-axis domain accordingly.
* The lower limit cannot be equal to or greater than the upper limit.
* The upper limit cannot be equal to or less than the lower limit.
* The reset button resets the y-axis to the minimum and maximum values in the data.

**Comment by dschwentker** [comment]
Tested all y-axis controls in all browsers.
