### ISSUE TITLE
Adjust y-axis limit controls to increment by a function of the data range

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/safety-outlier-explorer#62]
On y-axis upper and lower limit controls, the boxes contain arrows to adjust the limits by 1. This is not helpful when measures are reported in tenths or the range spans over 100

# Test notes
* When clicking the arrows in the y-axis limit inputs, the limits should increment by a reasonable factor of the y-axis range, or roughly 1/15 of the range.  For example, if the range is 150 the increment should be 10 and if the range is 1.5 the increment should be .1.

**Comment by danedexF5** [comment]
Used a variety of Y-Axis measures and the 1/15th calculation. Passed on all 3.
