### ISSUE TITLE
Firefox throwing tantrum over decimals

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/safety-outlier-explorer#63]
Firefox does not like decimals in the y-axis limit control boxes and highlights the box in red when a decimal is entered. Doesn't affect functionality - just needs a styling fix

**Comment by jwildfire** [comment]
## Test Notes

Confirm that numeric inputs are no longer red in firefox

**Comment by rchronowic** [comment]
Passed testing in Firefox and Chrome in CAT.

**Comment by rchronowic** [comment]
Tested this in Firefox and the box no longer outlines in red with decimals!

**Comment by dschwentker** [comment]
Per Ryan, tested and passed.
