### ISSUE TITLE
Make a footnote warning users when non-numeric records are removed

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/safety-outlier-explorer#79]
`src/onInit/cleanData.js` puts a note in console.log when removing non-numeric records, but it would be better if it was displayed for the user.  Maybe add a footnote?

# Test notes
* On the right side of the webpage between the controls and the chart a note should appear that details how many records with missing and/or non-numeric results were removed.
* The test dataset already contains missing records.  To test non-numeric records edit ADBDS.csv by adding non-numeric values to the STRESN column.

**Comment by danedexF5** [comment]
Added 2 non-numeric values to STRESN and they appear in the note to the right: "1201 records with a missing result and 2 records with a non-numeric result were removed." Approved.
